CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS titles (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL UNIQUE,
  min_kg integer NOT NULL,
  max_kg integer,
  description text NOT NULL
);

ALTER TABLE titles
  ALTER COLUMN max_kg DROP NOT NULL;

CREATE TABLE IF NOT EXISTS categories (
  id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  parent_id integer REFERENCES categories(id),
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  UNIQUE (parent_id, name)
);

CREATE TABLE IF NOT EXISTS users (
  id text PRIMARY KEY,
  nickname text NOT NULL,
  profile_image text,
  trust_score integer NOT NULL DEFAULT 50,
  kg_score integer NOT NULL DEFAULT 0,
  role text NOT NULL DEFAULT 'user',
  title_id integer REFERENCES titles(id),
  preferred_categories integer[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now()
);

ALTER TABLE users
  ADD COLUMN IF NOT EXISTS role text NOT NULL DEFAULT 'user';

CREATE TABLE IF NOT EXISTS restaurants (
  id text PRIMARY KEY,
  name text NOT NULL,
  category_id integer NOT NULL REFERENCES categories(id),
  address text NOT NULL,
  phone text,
  price_range text,
  business_hours text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS posts (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id),
  restaurant_id text NOT NULL REFERENCES restaurants(id),
  category_id integer NOT NULL REFERENCES categories(id),
  title text NOT NULL,
  content text NOT NULL,
  average_rating numeric(2, 1) NOT NULL DEFAULT 0,
  review_count integer NOT NULL DEFAULT 0,
  photo_count integer NOT NULL DEFAULT 0,
  like_count integer NOT NULL DEFAULT 0,
  kg_score integer NOT NULL DEFAULT 0,
  status text NOT NULL DEFAULT 'published',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  photos text[] NOT NULL DEFAULT '{}'
);

CREATE TABLE IF NOT EXISTS reviews (
  id text PRIMARY KEY,
  post_id text NOT NULL REFERENCES posts(id),
  user_id text NOT NULL REFERENCES users(id),
  rating integer NOT NULL CHECK (rating BETWEEN 1 AND 5),
  content text NOT NULL,
  photos text[] NOT NULL DEFAULT '{}',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS post_likes (
  user_id text NOT NULL REFERENCES users(id),
  post_id text NOT NULL REFERENCES posts(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, post_id)
);

CREATE TABLE IF NOT EXISTS post_scraps (
  user_id text NOT NULL REFERENCES users(id),
  post_id text NOT NULL REFERENCES posts(id),
  created_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, post_id)
);

CREATE TABLE IF NOT EXISTS auth_accounts (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id),
  provider text NOT NULL,
  provider_user_id text NOT NULL,
  email text,
  access_token_enc text NOT NULL DEFAULT '',
  refresh_token_enc text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (provider, provider_user_id)
);

CREATE TABLE IF NOT EXISTS ai_recommendation_logs (
  id text PRIMARY KEY,
  user_id text NOT NULL REFERENCES users(id),
  request_context jsonb NOT NULL,
  candidate_restaurant_ids text[] NOT NULL DEFAULT '{}',
  final_recommendation jsonb NOT NULL,
  model_name text NOT NULL,
  prompt_version text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

INSERT INTO titles (name, min_kg, max_kg, description) VALUES
  ('입문자', 0, 9, '첫 발을 뗀 쩝쩝러'),
  ('탐험가', 10, 29, '새로운 맛집을 넓게 탐색'),
  ('맛잘알', 30, 49, '맛의 기준이 있는 사용자'),
  ('쩝쩝러', 50, 99, '자주 기록하고 추천하는 사용자'),
  ('쩝쩝박사', 100, NULL, '누적 활동이 높은 핵심 유저')
ON CONFLICT (name) DO UPDATE SET
  min_kg = EXCLUDED.min_kg,
  max_kg = EXCLUDED.max_kg,
  description = EXCLUDED.description;

UPDATE users
SET title_id = CASE
  WHEN kg_score BETWEEN 0 AND 9 THEN (SELECT id FROM titles WHERE name = '입문자')
  WHEN kg_score BETWEEN 10 AND 29 THEN (SELECT id FROM titles WHERE name = '탐험가')
  WHEN kg_score BETWEEN 30 AND 49 THEN (SELECT id FROM titles WHERE name = '맛잘알')
  WHEN kg_score BETWEEN 50 AND 99 THEN (SELECT id FROM titles WHERE name = '쩝쩝러')
  ELSE (SELECT id FROM titles WHERE name = '쩝쩝박사')
END
WHERE title_id IS NOT NULL;

DELETE FROM titles
WHERE name IN ('쩝쩝학사', '쩝쩝석사', '쩝쩝교수');

INSERT INTO categories (id, name, parent_id, sort_order) VALUES
  (1, '맛집', NULL, 1),
  (2, '카페', NULL, 2),
  (3, '술집', NULL, 3)
ON CONFLICT (id) DO UPDATE SET
  name = EXCLUDED.name,
  parent_id = EXCLUDED.parent_id,
  sort_order = EXCLUDED.sort_order,
  is_active = true;

INSERT INTO categories (name, parent_id, sort_order) VALUES
  ('한식', 1, 1),
  ('중식', 1, 2),
  ('일식', 1, 3),
  ('양식', 1, 4),
  ('디저트', 2, 1),
  ('에스프레소바', 2, 2),
  ('이자카야', 3, 1),
  ('요리주점', 3, 2)
ON CONFLICT (parent_id, name) DO UPDATE SET
  sort_order = EXCLUDED.sort_order,
  is_active = true;

WITH development_accounts(user_id, auth_id, code, nickname, email, preferred_category_names) AS (
  VALUES
    ('user_dev_login', 'auth_dev_login', 'dev-login', '개발로그인', 'dev-login@example.com', ARRAY['일식', '양식']::text[]),
    ('user_demo_01', 'auth_demo_01', 'demo-user-01', '데모유저1', 'demo1@example.com', ARRAY['양식', '일식']::text[]),
    ('user_demo_02', 'auth_demo_02', 'demo-user-02', '데모유저2', 'demo2@example.com', ARRAY['중식', '술집']::text[]),
    ('user_demo_03', 'auth_demo_03', 'demo-user-03', '데모유저3', 'demo3@example.com', ARRAY['일식', '중식']::text[]),
    ('user_demo_04', 'auth_demo_04', 'demo-user-04', '데모유저4', 'demo4@example.com', ARRAY['술집', '양식']::text[]),
    ('user_demo_05', 'auth_demo_05', 'demo-user-05', '데모유저5', 'demo5@example.com', ARRAY['양식', '중식']::text[])
),
prepared_accounts AS (
  SELECT
    account.user_id,
    account.auth_id,
    account.code,
    account.nickname,
    account.email,
    COALESCE(array_agg(category.id ORDER BY array_position(account.preferred_category_names, category.name)) FILTER (WHERE category.id IS NOT NULL), '{}') AS preferred_category_ids
  FROM development_accounts account
  LEFT JOIN categories category ON category.name = ANY(account.preferred_category_names)
  GROUP BY account.user_id, account.auth_id, account.code, account.nickname, account.email, account.preferred_category_names
),
upserted_users AS (
  INSERT INTO users (id, nickname, profile_image, trust_score, kg_score, role, title_id, preferred_categories)
  SELECT
    user_id,
    nickname,
    NULL,
    50,
    0,
    'user',
    (SELECT id FROM titles WHERE name = '입문자' LIMIT 1),
    preferred_category_ids::integer[]
  FROM prepared_accounts
  ON CONFLICT (id) DO UPDATE SET
    nickname = EXCLUDED.nickname,
    role = EXCLUDED.role,
    title_id = COALESCE(users.title_id, EXCLUDED.title_id),
    preferred_categories = EXCLUDED.preferred_categories
  RETURNING id
)
INSERT INTO auth_accounts (id, user_id, provider, provider_user_id, email, access_token_enc, refresh_token_enc)
SELECT
  auth_id,
  user_id,
  'gachon',
  'gachon_' || code,
  email,
  '',
  ''
FROM prepared_accounts
ON CONFLICT (provider, provider_user_id) DO UPDATE SET
  user_id = EXCLUDED.user_id,
  email = EXCLUDED.email;

SELECT setval(pg_get_serial_sequence('titles', 'id'), COALESCE((SELECT max(id) FROM titles), 1), true);
SELECT setval(pg_get_serial_sequence('categories', 'id'), COALESCE((SELECT max(id) FROM categories), 1), true);

CREATE INDEX IF NOT EXISTS categories_parent_id_idx ON categories(parent_id);
CREATE INDEX IF NOT EXISTS posts_category_id_idx ON posts(category_id);
CREATE INDEX IF NOT EXISTS posts_restaurant_id_idx ON posts(restaurant_id);
CREATE INDEX IF NOT EXISTS reviews_post_id_idx ON reviews(post_id);
CREATE UNIQUE INDEX IF NOT EXISTS reviews_post_user_idx ON reviews(post_id, user_id);
CREATE INDEX IF NOT EXISTS post_likes_post_id_idx ON post_likes(post_id);
CREATE INDEX IF NOT EXISTS post_scraps_post_id_idx ON post_scraps(post_id);
CREATE INDEX IF NOT EXISTS ai_recommendation_logs_user_id_idx ON ai_recommendation_logs(user_id);
